export const MOCK_RETURN_DATA = {
  statusCode: "0",
  statusDescription: "SUCCESS",
  additionalStatuses: null,
  badgesEarned: [
    {
      id: 2,
      name: "Page Enthusiast",
      description: "Read 1000 pages",
      threshold: 1000,
      type: "PAGES",
      tier: 2,
      imageUrl: "/badges/Pages/Pages_2.png",
      pointsAwarded: 20,
      nextBadge: {
        id: 3,
        name: "Readaholic",
        description: "Read 5,000 pages",
        threshold: 5000,
        type: "PAGES",
        tier: 3,
        imageUrl: "/badges/Pages/Pages_3.png",
        pointsAwarded: 50,
      },
    },
    {
      id: 36,
      name: "Challenge Starter",
      description: "Complete 1 challenge",
      threshold: 1,
      type: "CHALLENGES",
      tier: 1,
      imageUrl: "/badges/Challenges/Challenges_1.svg",
      pointsAwarded: 10,
      nextBadge: {
        id: 37,
        name: "Challenge Enthusiast",
        description: "Complete 5 challenges",
        threshold: 5,
        type: "CHALLENGES",
        tier: 2,
        imageUrl: "/badges/Challenges/Challenges_2.svg",
        pointsAwarded: 20,
      },
    },
    {
      id: 32,
      name: "Badge Enthusiast",
      description: "Collect 5 badges",
      threshold: 5,
      type: "COMPLETION",
      tier: 2,
      imageUrl: "/badges/Completion/Completion_2.png",
      pointsAwarded: 20,
      nextBadge: {
        id: 33,
        name: "Badge Collector",
        description: "Collect 10 badges",
        threshold: 10,
        type: "COMPLETION",
        tier: 3,
        imageUrl: "/badges/Completion/Completion_3.png",
        pointsAwarded: 50,
      },
    },
  ],
  challenges: [
    {
      id: 1,
      userChallengeId: 1,
      name: "Daily Reading Challenge",
      description: "Read every day for a week",
      frequency: "Daily",
      type: "Streak",
      threshold: 7,
      duration: 7,
      challengeStartDate: "null",
      challengeEndDate: "null",
      pointsAwarded: 50,
      userChallengeStartDate: "2023-09-10T10:00",
      userChallengeEndDate: "2023-09-16T23:59:59",
      status: "FAILED_CHALLENGE",
      dateProgress: null,
      additionalInfo: null,
    },
    {
      id: 1,
      userChallengeId: 2,
      name: "Daily Reading Challenge",
      description: "Read every day for a week",
      frequency: "Daily",
      type: "Streak",
      threshold: 7,
      duration: 7,
      challengeStartDate: "null",
      challengeEndDate: "null",
      pointsAwarded: 50,
      userChallengeStartDate: "2023-10-20T17:01:38.631423",
      userChallengeEndDate: "2023-10-26T23:59:59",
      status: "STARTED_CHALLENGE",
      dateProgress: {
        progress: 28.57142857142857,
        daysCompleted: 2,
        daysRemaining: 5,
      },
      additionalInfo: {
        done: 2.0,
        toGo: 5.0,
        percentComplete: 28.57142857142857,
      },
    },
    {
      id: 2,
      userChallengeId: 3,
      name: "Weekly Reading Challenge",
      description: "Read at least 250 pages in a week",
      frequency: "Weekly",
      type: "Pages",
      threshold: 250,
      duration: 7,
      challengeStartDate: "null",
      challengeEndDate: "null",
      pointsAwarded: 100,
      userChallengeStartDate: "2023-10-20T17:01:38.631423",
      userChallengeEndDate: "2023-10-26T23:59:59",
      status: "COMPLETED_CHALLENGE",
      dateProgress: {
        progress: 28.57142857142857,
        daysCompleted: 2,
        daysRemaining: 5,
      },
      additionalInfo: null,
    },
    {
      id: 3,
      userChallengeId: 4,
      name: "Monthly Reading Challenge",
      description: "Read 5 books in a month",
      frequency: "Monthly",
      type: "Books",
      threshold: 5,
      duration: 30,
      challengeStartDate: "null",
      challengeEndDate: "null",
      pointsAwarded: 200,
      userChallengeStartDate: "2023-10-16T17:01:38.631423",
      userChallengeEndDate: "2023-11-14T23:59:59",
      status: "STARTED_CHALLENGE",
      dateProgress: {
        progress: 20.0,
        daysCompleted: 6,
        daysRemaining: 24,
      },
      additionalInfo: {
        done: 1.0,
        toGo: 4.0,
        percentComplete: 20.0,
      },
    },
  ],
};
